version: '3.8'

services:

  backend:
    build: .
    #depends_on:
      #- postgres
      #- redis
    ports:
      - 8000:8000
    networks:
      - app_network

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=ironman
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    networks:
      - app_network

  redis:
     image: redis:latest
     ports: 
       - 6379:6379
     networks:
       - app_network

networks:
  app_network:
    driver: bridge
